# laboratoire.yml
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8090
spring:
  application:
    name: laboratoires
#  datasource:
#    url: jdbc:postgresql://laboratoires-db:5433/laboratories
#    username: postgres
#    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

#application:
#  config:
#    laboratoires-url: http://gateway:8080/api/v1/laboratoires

management:
  tracing:
    sampling:
      probability: 1.0