eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8070
spring:
  application:
    name: utilisateurs
  datasource:
    url: jdbc:postgresql://utilisateurs-db:5432/utilisateurs
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    utilisateurs-url: http://gateway:8080/api/v1/utilisateurs

management:
  tracing:
    sampling:
      probability: 1.0